name: model_tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "rwth-i6/i6_models"
          path: ""
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - run: |
          pip install pytest
          pip install typeguard librosa torch==1.13.1 onnx=1.13.1 onnxruntime=1.13.1
      - name: Test Models
        run: |
          python -m pytest tests
