name: model_tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "rwth-i6/i6_models"
          path: ""
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - run: |
          pip install pytest
          pip install -r requirements.txt
          # Older Numpy 1 requires those older versions. (https://github.com/rwth-i6/i6_models/issues/78)
          pip install ctc-segmentation==1.6.6 pyworld==0.3.4 numpy==1.23.5
          pip install -r requirements_dev.txt
      - name: Test Models
        run: |
          python -m pytest tests
