name: Publish

on:
  workflow_run:
    workflows: ["model_tests"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push' &&
      github.repository == 'rwth-i6/i6_models'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python deps
      run: |
        echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
        pip3 install --user --upgrade pip setuptools wheel twine

    - run: python3 setup.py sdist

    # https://github.com/marketplace/actions/pypi-publish
    - name: Publish to PyPI
      # https://github.com/pypa/gh-action-pypi-publish/issues/112
      uses: pypa/gh-action-pypi-publish@release/v1.4
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
